### ISSUE TITLE
Add support for Atmel RZUSBSTICK

### ISSUE THREAD

**Issue by SamZorSec** [IoTsec/Z3sec#1]
Hi,
At first, I would like to thank you for your work, it seems to be a great tool. I'm trying to use it with two Atmel RZUSBSTICK, which are running the KillerBee firmware.

I've modified the arg_type.py file and commented most of the code inside the `kb_dev()` function.
arg_type.py
```
def kb_dev(string):
    if not string.startswith("/dev/ttyUSB"):
        msg = "%r does not start with '/dev/ttyUSB'. Use 'zbid' to find a valid device string." % string
        raise argparse.ArgumentTypeError(msg)
    if not os.path.exists(string):
        msg = "%r does not exist. Use 'zbid' to find a valid device string." % string
        raise argparse.ArgumentTypeError(msg)
return string
```

Then, when I try to execute the `z3sec_touchlink" tool, a semantic error occurs.
```
sudo z3sec_touchlink --kb "1:8" --kb "3:12" -c "20" scan
Setting up DualRadio:
KillerBee Radio (send): 1:8
Warning: You are using pyUSB 1.x, support is in beta.
KillerBee Radio (recv): 3:12
Traceback (most recent call last):
  File "/usr/local/bin/z3sec_touchlink", line 4, in <module>
    __import__('pkg_resources').run_script('z3sec==0.1', 'z3sec_touchlink')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1510, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/z3sec-0.1-py2.7.egg/EGG-INFO/scripts/z3sec_touchlink", line 583, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/z3sec-0.1-py2.7.egg/EGG-INFO/scripts/z3sec_touchlink", line 576, in main
    
  File "build/bdist.linux-x86_64/egg/z3sec/radios.py", line 360, in __init__
  File "build/bdist.linux-x86_64/egg/z3sec/radios.py", line 331, in sniffer_off
  File "build/bdist.linux-x86_64/egg/killerbee/__init__.py", line 253, in sniffer_off
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 344, in sniffer_off
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 313, in _close_stream
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 286, in __usb_write
Exception: Error: Semantical Error
```

Thanks for your help,
Sam

**Comment by pH-T** [comment]
Hi, 
I ran into the same problem... 
Have you found any solution (other than re-implementing)?
Thank you,
pH

**Comment by SamZorSec** [comment]
Hi @pH-T,
I didn't have found a solution and I'm not working anymore on ZigBee.
Sam

**Comment by rychardeh** [comment]
I have exactly the same issue on an installation where killerbee works fine.  The README states that it wasn't tested with RZRAVEN and that is clear from kb_dev().  However, even after modifying that so it does correctly select RZRAVEN and use dev_rzusbstick.py, I can't see anything amiss compared with, say zbstumbler or zbdump, which run OK.
